using System.Collections.Generic;
using Sirenix.OdinInspector;
using UnityEngine;

namespace Plugins.SceneService
{
    [CreateAssetMenu(menuName = "Game/Scene Settings", fileName = "SceneSettings")]
    public class SceneSettings : ScriptableObject
    {
        [SerializeField] [InlineEditor] private List<SceneData> _scenes = new();

        public IReadOnlyList<SceneData> Scenes => _scenes;

        public SceneData GetData(string id)
        {
            foreach (var scene in _scenes)
                if (scene.Id == id) return scene;
            return null;
        }

#if UNITY_EDITOR
        [Button]
        private void Refresh()
        {
            _scenes.Clear();

            var guids = UnityEditor.AssetDatabase.FindAssets("t:SceneData");
            foreach (var guid in guids)
            {
                var path  = UnityEditor.AssetDatabase.GUIDToAssetPath(guid);
                var asset = UnityEditor.AssetDatabase.LoadAssetAtPath<SceneData>(path);
                if (asset != null)
                    _scenes.Add(asset);
            }

            UnityEditor.EditorUtility.SetDirty(this);
            UnityEditor.AssetDatabase.SaveAssetIfDirty(this);

            RegenerateSceneTypeFile();

            Debug.Log($"[SceneSettings] Refreshed {_scenes.Count} SceneData asset(s).");
        }

        private void RegenerateSceneTypeFile()
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("// THIS CLASS IS AUTOGENERATED");
            sb.AppendLine("namespace Plugins.SceneService");
            sb.AppendLine("{");
            sb.AppendLine("    public static class SceneType");
            sb.AppendLine("    {");
            foreach (var scene in _scenes)
            {
                var raw        = System.Text.RegularExpressions.Regex.Replace(scene.Id, @"[^a-zA-Z0-9_]", "_");
                var identifier = char.ToUpper(raw[0]) + raw.Substring(1);
                sb.AppendLine($"        public const string {identifier} = \"{scene.Id}\";");
            }
            sb.AppendLine("    }");
            sb.Append("}");

            const string assetPath = "Assets/!_Project/Backend/SceneService/SceneType.cs";
            System.IO.File.WriteAllText(
                System.IO.Path.Combine(UnityEngine.Application.dataPath, "../" + assetPath),
                sb.ToString()
            );
            UnityEditor.AssetDatabase.ImportAsset(assetPath);
        }
#endif
    }
}
