// THIS CLASS IS AUTOGENERATED
namespace Backend.Systems.Audio
{
    public static class AudioType
    {
        public const string Beep = "beep";
        public const string Button_press = "button_press";
    }
}