// THIS CLASS IS AUTOGENERATED
namespace Plugins.AudioService
{
    public static class AudioType
    {
        public const string Beep = "beep";
        public const string Button_press = "button_press";
        public const string Warning = "warning";
    }
}