// THIS CLASS IS AUTOGENERATED
namespace Backend.Systems.Currency
{
    public static class CurrencyType
    {
        public const string Gem = "gem";
        public const string Gold = "gold";
    }
}