// THIS CLASS IS AUTOGENERATED
namespace Backend.Systems.Panel
{
    public static class PanelType
    {
        public const string GamePlay = "GamePlay";
        public const string Setting = "Setting";
    }
}