// THIS CLASS IS AUTOGENERATED
namespace Backend.Systems.Panel
{
    public static class PanelType
    {
        public const string Panel_Complete = "Panel-Complete";
        public const string Panel_GamePlay = "Panel-GamePlay";
        public const string Panel_Home = "Panel-Home";
        public const string Panel_Setting = "Panel-Setting";
    }
}