// THIS CLASS IS AUTOGENERATED
namespace Plugins.PanelService
{
    public static class PanelType
    {
        public const string Complete = "complete";
        public const string Setting = "setting";
    }
}