using System.Collections.Generic;
using Sirenix.OdinInspector;
using UnityEngine;

namespace Plugins.PanelService
{
    [CreateAssetMenu(menuName = "Game/Panel Settings", fileName = "PanelSettings")]
    public class PanelServiceSettings : ScriptableObject
    {
        [SerializeField] [InlineEditor] private List<BasePanel> _panels = new();

        public IReadOnlyList<BasePanel> Panels => _panels;

        public BasePanel GetPrefab(string id)
        {
            foreach (var panel in _panels)
                if (panel.Id == id) return panel;
            return null;
        }

#if UNITY_EDITOR
        [Button]
        private void Refresh()
        {
            _panels.Clear();

            var guids = UnityEditor.AssetDatabase.FindAssets("t:Prefab");
            foreach (var guid in guids)
            {
                var path = UnityEditor.AssetDatabase.GUIDToAssetPath(guid);
                var prefab = UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (prefab == null) continue;
                var panel = prefab.GetComponent<BasePanel>();
                if (panel != null)
                    _panels.Add(panel);
            }

            UnityEditor.EditorUtility.SetDirty(this);
            UnityEditor.AssetDatabase.SaveAssetIfDirty(this);

            RegeneratePanelTypeFile();

            Debug.Log($"[PanelSettings] Refreshed {_panels.Count} BasePanel prefab(s).");
        }

        private void RegeneratePanelTypeFile()
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("// THIS CLASS IS AUTOGENERATED");
            sb.AppendLine("namespace Plugins.PanelService");
            sb.AppendLine("{");
            sb.AppendLine("    public static class PanelType");
            sb.AppendLine("    {");
            foreach (var panel in _panels)
            {
                if (string.IsNullOrEmpty(panel.Id)) continue;
                var raw = System.Text.RegularExpressions.Regex.Replace(panel.Id, @"[^a-zA-Z0-9_]", "_");
                var identifier = char.ToUpper(raw[0]) + raw.Substring(1);
                sb.AppendLine($"        public const string {identifier} = \"{panel.Id}\";");
            }

            sb.AppendLine("    }");
            sb.Append("}");

            const string assetPath = "Assets/!_Project/Backend/PanelService/PanelType.cs";
            System.IO.File.WriteAllText(
                System.IO.Path.Combine(Application.dataPath, "../" + assetPath),
                sb.ToString()
            );
            UnityEditor.AssetDatabase.ImportAsset(assetPath);
        }
#endif
    }
}