#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Game.Editor
{
    public static class EditorUtilities
    {
        /// <summary>
        /// Finds all assets of type <typeparamref name="T"/>, populates <paramref name="list"/>,
        /// marks the owner dirty, and regenerates a static constants file.
        /// </summary>
        public static void RefreshAssets<T>(
            ScriptableObject owner,
            List<T> list,
            System.Func<T, string> getId,
            string generatedClassName,
            string logTag) where T : Object
        {
            list.Clear();

            var guids = AssetDatabase.FindAssets($"t:{typeof(T).Name}");
            foreach (var guid in guids)
            {
                var path  = AssetDatabase.GUIDToAssetPath(guid);
                var asset = AssetDatabase.LoadAssetAtPath<T>(path);
                if (asset != null)
                    list.Add(asset);
            }

            EditorUtility.SetDirty(owner);
            AssetDatabase.SaveAssetIfDirty(owner);

            var ownerScript     = MonoScript.FromScriptableObject(owner);
            var ownerDir        = Path.GetDirectoryName(AssetDatabase.GetAssetPath(ownerScript));
            var ownerNamespace  = ownerScript.GetClass().Namespace;
            var outputPath      = $"{ownerDir}/{generatedClassName}.cs";
            RegenerateConstantsFile(list, getId, ownerNamespace, generatedClassName, outputPath);

            Debug.Log($"[{logTag}] Refreshed {list.Count} {typeof(T).Name} asset(s).");
        }

        private static void RegenerateConstantsFile<T>(
            List<T> items,
            System.Func<T, string> getId,
            string namespaceName,
            string className,
            string assetPath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// THIS CLASS IS AUTOGENERATED");
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");
            foreach (var item in items)
            {
                var id         = getId(item);
                var raw        = Regex.Replace(id, @"[^a-zA-Z0-9_]", "_");
                var identifier = char.ToUpper(raw[0]) + raw.Substring(1);
                sb.AppendLine($"        public const string {identifier} = \"{id}\";");
            }
            sb.AppendLine("    }");
            sb.Append("}");

            File.WriteAllText(
                Path.Combine(Application.dataPath, "../" + assetPath),
                sb.ToString()
            );
            AssetDatabase.ImportAsset(assetPath);
        }
    }
}
#endif
