using System.Collections.Generic;
using Sirenix.OdinInspector;
using UnityEngine;
using UnityEngine.Audio;

namespace Plugins.AudioService
{
    [CreateAssetMenu(menuName = "Game/Audio Settings", fileName = "AudioSettings")]
    public class AudioSettings : ScriptableObject
    {
        [SerializeField] private AudioMixer _mixer;
        [SerializeField] [Range(0f, 1f)] private float _defaultVolume = 1f;
        [SerializeField] [InlineEditor] private List<AudioData> _clips = new();

        public AudioMixer Mixer => _mixer;
        public float DefaultVolume => _defaultVolume;
        public IReadOnlyList<AudioData> Clips => _clips;

        public AudioData GetData(string id)
        {
            foreach (var clip in _clips)
                if (clip.Id == id) return clip;
            return null;
        }

#if UNITY_EDITOR
        [Button]
        private void Refresh()
        {
            _clips.Clear();

            var guids = UnityEditor.AssetDatabase.FindAssets("t:AudioData");
            foreach (var guid in guids)
            {
                var path = UnityEditor.AssetDatabase.GUIDToAssetPath(guid);
                var asset = UnityEditor.AssetDatabase.LoadAssetAtPath<AudioData>(path);
                if (asset != null)
                    _clips.Add(asset);
            }

            UnityEditor.EditorUtility.SetDirty(this);
            UnityEditor.AssetDatabase.SaveAssetIfDirty(this);

            RegenerateAudioTypeFile();

            Debug.Log($"[AudioSettings] Refreshed {_clips.Count} AudioData asset(s).");
        }

        private void RegenerateAudioTypeFile()
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("// THIS CLASS IS AUTOGENERATED");
            sb.AppendLine("namespace Plugins.AudioService");
            sb.AppendLine("{");
            sb.AppendLine("    public static class AudioType");
            sb.AppendLine("    {");
            foreach (var audio in _clips)
            {
                var raw = System.Text.RegularExpressions.Regex.Replace(audio.Id, @"[^a-zA-Z0-9_]", "_");
                var identifier = char.ToUpper(raw[0]) + raw.Substring(1);
                sb.AppendLine($"        public const string {identifier} = \"{audio.Id}\";");
            }
            sb.AppendLine("    }");
            sb.Append("}");

            const string assetPath = "Assets/!_Project/Backend/AudioService/Scripts/AudioType.cs";
            System.IO.File.WriteAllText(
                System.IO.Path.Combine(UnityEngine.Application.dataPath, "../" + assetPath),
                sb.ToString()
            );
            UnityEditor.AssetDatabase.ImportAsset(assetPath);
        }
#endif
    }
}
